config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get '/auth/facebook/callback' => 'sessions#fb_create'
  resources :users do
    collection do
      get 'active'
      get 'inactive'
    end
  end
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    resources :locations, only: [:show, :index, :new, :edit]
    resources :sports, only: [:show, :index, :new, :edit]
    resources :events, only: [:show, :index, :new, :edit]
  end
  
  resources :sessions, only:[:new, :create, :destroy]
  resources :sports, only: [:index, :show, :new, :create, :edit, :update]
  resources :locations, only: [:index, :show, :new, :create, :edit, :update]
  resources :events, only: [:index, :show, :new, :create, :edit, :update]
  resources :comments
  resources :questions
end

app/models/sport.rb
class Sport < ApplicationRecord
  
  validates :name,  :presence => true, 
                        :uniqueness => true
  validates :description,  :presence => true
  
  belongs_to :user
  has_many :events
  has_many :users, through: :events
  
  scope :search, -> (search_text) {Sport.where("name LIKE ?", "%" + search_text + "%") }

end

app/models/sports.rb
class User < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  skip_before_action :authorized, only: [:index]

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)
    if @sport.save
      redirect_to sport_url(@sport)
    else
      render :new
    end
  end

  def edit
    @sport = Sport.find(params[:id])
    if !owns_record(@sport)
      redirect_to sports_url
    end
  end

  def update
    @sport = Sport.find(params[:id])
    if @sport.valid? && current_user && owns_record(@sport)
      if params[:commit] != "Edit"
        @sport.update(sport_params)
        redirect_to sport_url
      else
        redirect_to edit_sport_url
      end
    else
      render :new
    end
  end

  def show
    @sport = Sport.find(params[:id])
  end

  def index
    if params[:user_id]
      @sports = User.find(params[:user_id]).sports
    else
      @sports = Sport.all
    end
  end
 
  private
 
  def sport_params
    params.require(:sport).permit(:name, :description).merge(user_id: session[:user_id])
  end


end

app/helpers/sports_helper.rb
module SportsHelper
  def new_sport_button_url
    params[:user_id] ? new_user_sport_url : new_sport_url
  end

  def show_sport_button_url(event)
    case params.has_key?(:user_id)
      when true
        '/users/' + params[:user_id].to_s + '/sports/' + event.id.to_s 
      when false
        '/sports/' + event.id.to_s
    end     
  end

  def edit_sport_button_url(event)
    case params.has_key?(:user_id)
      when true
        '/users/' + params[:user_id].to_s + '/sports/' + event.id.to_s + '/edit'
      when false
        '/sports/' + event.id.to_s + '/edit'
    end     
  end
end

app/views/sports/_form.html.erb
<%= form_with model: @sport do |f| %>
  <% if current_page?(:controller => controller_name, :action => 'new') %>
    <label>Creating New Sport:</label><br>  
  <% elsif current_page?(:controller => controller_name, :action => 'edit')%>
    <label>Editing Sport:</label><br> 
  <% end %>
  <div class="<%= ' field_with_errors' if @sport.errors[:name].any? %>">
    <label>Sport Name:</label><br>
    <%= label_text_field(@sport, f, :name) %><br>
  </div>
  <div class="<%= ' field_with_errors' if @sport.errors[:description].any? %>">
    <label>Description:</label><br>
    <%= label_text_field(@sport, f, :description) %><br>
  </div>
  <% if !current_page?(:controller => controller_name, :action => 'show', :id => @sport.id.to_s)%>
     <% params[:form_action] = :action %>
  <% else %>
    <% params[:form_action] = "show"%>
  <% end %>
  <% if owns_record(@sport) then %>
    <%= f.submit  submit_text(@sport) %>
  <%end%>
<% end %>

app/views/sports/edit.html.erb
<%= render partial: 'form' %>

app/views/sports/index.html.erb
<h1>Sports</h1>
<%= form_tag sports_path, method:"get" do %>
  <label>Search Sports:</label><br>
  <input type="text" id="sport_search" name="sport[search_text]"><br> 
  <input type="submit" value="Submit Search">
<% end %>
<br>
<%if current_user then%> 
  <div style="float:left; width: auto;">
    <%= button_to "New", new_sport_button_url, method: :get%>
  </div>
<%end%>
<br><br>
<% @sports.each do |s|%>
  <div style="float:left; width: auto;">
    <%= s.name %> <%= s.description%> 
  </div>
  <%if current_user then%> 
    <div style="float:left; width: auto;">
      <%= button_to "View", show_sport_button_url(s), method: :get%>
    </div>
    <%if owns_record(s) then %>
      <div style="float:left; width: auto;">
        <%= button_to "Edit", edit_sport_button_url(s), method: :get%>
      </div><br><br>
    <%end%>
  <%end%>
  <br><br>
<% end %>

app/views/sports/new.html.erb
<%= render partial: 'layouts/error', locals: {form_model: @sport}%>
<%= render partial: 'form' %>