config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get '/auth/facebook/callback' => 'sessions#fb_create'
  resources :users do
    collection do
      get 'active'
      get 'inactive'
    end
  end
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    resources :locations, only: [:show, :index, :new, :edit]
    resources :sports, only: [:show, :index, :new, :edit]
    resources :events, only: [:show, :index, :new, :edit]
  end
  
  resources :sessions, only:[:new, :create, :destroy]
  resources :sports, only: [:index, :show, :new, :create, :edit, :update]
  resources :locations, only: [:index, :show, :new, :create, :edit, :update]
  resources :events, only: [:index, :show, :new, :create, :edit, :update]
  resources :comments
  resources :questions
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :events
  has_many :locations, through: :events
  has_many :sports, through: :events
  has_many :sports
  has_many :locations
  
  validates :username,  :presence => true, 
                        :uniqueness => true
  validates :first_name, :presence => true
  validates :email, :presence => true, 
                    :uniqueness => true, 
                    email: true
  validates :password,  :presence => true, 
                    :allow_blank => true,
                    :length => {:within => 4..40},
                    :on => [:update]
  validates :password,  :presence => true, 
                        :confirmation => true,
                        :length => {:within => 4..40},
                        :on => :create
  
  
  has_secure_password

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.valid?      
      if params[:commit] != "Edit"
        @user.update(user_params)        
        
        redirect_to user_url
      else
        redirect_to edit_user_url
      end
    else
      render :new
    end
  end

  def show    
    @user = User.find(params[:id])
    if params[:id] != current_user.id.to_s && is_admin == false
      redirect_to not_admin_user_url
    end
  end

  def index
    if is_admin
      @users = User.all
    else
      redirect_to not_admin_user_url
    end
  end

  def active
    @users = User.all.active
  end

  def inactive
    @users = User.all.inactive
  end
 
  private
 
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :active, :admin)
  end

  def not_admin_user_url
    '/users/' + current_user.id.to_s
  end
  
  def valid_commit
    params[:commit] != "Edit" || params[:commit]
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def is_admin
    current_user == nil ? false : current_user.admin
  end
end

app/views/users/_form.html.erb
<%= form_for (@user) do |f| %>
  <% if current_page?(:controller => 'users', :action => 'new') %>
    <label>Creating New User:</label><br>  
  <% elsif current_page?(:controller => 'users', :action => 'edit')%>
    <label>Editing User:</label><br> 
  <% end %>
  <div class="<%= ' field_with_errors' if @user.errors[:username].any? %>">
    <label>UserName:</label><br>
    <%= label_text_field(@user, f, :username) %><br>
  </div>
  <div class="<%= ' field_with_errors' if @user.errors[:first_name].any? %>">
    <label>First Name:</label><br>
    <%= label_text_field(@user, f, :first_name) %><br>
  </div>
  <label>Last Name:</label><br>
   <%= label_text_field(@user, f, :last_name) %><br>
  <div class="<%= ' field_with_errors' if @user.errors[:email].any? %>">
    <label>Email:</label><br>
    <%= label_text_field(@user, f, :email) %><br>
  </div>
   <% if !current_page?(:controller => 'users', :action => 'new') %>
    <div>
      <label>Active:</label><br>
      <%= f.check_box :active%>
    </div>
  <%end%>
  <% if !current_page?(:controller => 'users', :action => 'new') && is_admin%>
    <div>
      <label>Admin:</label><br>
      <%= f.check_box :admin%>
    </div>
  <%end%>
  <% if !current_page?(:controller => controller_name, :action => 'show', :id => @user.id.to_s) %>
    <div class="<%= ' field_with_errors' if @user.errors[:password].any? %>">
      <label>Password:</label><br>
      <%= f.password_field  :password %><br>
      <%= f.password_field  :password_confirmation %><br> 
    </div>
     <% params[:form_action] = :action %>
  <% else %>
    <% params[:form_action] = "show"%>
  <% end %>
  <%= f.submit  submit_text(@user) %>
<% end %>
<p></p>
<div style="float:left; width: auto;">
  <%= button_to "my Sports", nested_user_url("sports"), method: :get%>
</div>
<div style="float:left; width: auto;">
  <%= button_to "my Locations", nested_user_url("locations"), method: :get%>
</div>
<div style="float:left; width: auto;">
  <%= button_to "my Events", nested_user_url("events"), method: :get%>
</div>

app/views/users/_list.html.erb
<%if !current_page?(:controller => controller_name, :action => 'index')%>
  <div style="float:left; width: auto;">
    <%= button_to "All Users", users_url , method: :get%>
  </div>
<%end%>
<%if !current_page?(:controller => controller_name, :action => 'active')%>
  <div style="float:left; width: auto;">
    <%= button_to "Active Users", active_users_url , method: :get%>
  </div>
<%end%>
<%if !current_page?(:controller => controller_name, :action => 'inactive')%>
  <div style="float:left; width: auto;">
    <%= button_to "InActive Users", inactive_users_url , method: :get%>
  </div>
<%end%>
<br><br>
<% @users.each do |u|%>
  <div style="float:left; width: auto;">
    <%= u.first_name %> <%= u.last_name%> 
  </div>
  <div style="float:left; width: auto;">
    <%= button_to "View", user_url(u), method: :get%>
  </div>
  <div style="float:left; width: auto;">
    <%= button_to "Edit", edit_user_url(u), method: :get%>
  </div>
  <br><br>
<% end %>

app/views/users/active.html.erb
<h1>Active Users</h1>
<%= render partial: 'list' %>

app/views/users/inactive.html.erb
<h1>InActive Users</h1>
<%= render partial: 'list' %>

app/views/users/index.html.erb
Users Index

app/views/users/new.html.erb
<%= render partial: 'layouts/error', locals: {form_model: @user}%>
<%= render partial: 'form' %>